### ISSUE TITLE
김연구 과제 제출

### ISSUE THREAD

**Issue by yg-0103** [ai-creatv/algorithm_FDS18#12]
<img width="1440" alt="스크린샷 2021-03-07 오후 7 07 58" src="https://user-images.githubusercontent.com/71420665/110236345-8d65e380-7f78-11eb-9e6d-9c30c76cebff.png">

예전에 했는데 도전이 다시 안돼서 이것만 첨부드립니다... ㅠㅠ

**Comment by ai-creatv** [comment]
수고하셨습니다! :)
