### ISSUE TITLE
최수혁 과제제출 입니다.

### ISSUE THREAD

**Issue by choisuhyeok1255** [ai-creatv/algorithm_FDS18#14]
[모의고사](https://github.com/choisuhyeok1255/programmers/blob/main/%EB%AA%A8%EC%9D%98%EA%B3%A0%EC%82%AC.js)

[이상한 문자 만들기](https://github.com/choisuhyeok1255/programmers/blob/main/%EC%9D%B4%EC%83%81%ED%95%9C%EB%AC%B8%EC%9E%90%EB%A7%8C%EB%93%A4%EA%B8%B0.js)

**Comment by ai-creatv** [comment]
기능 구현을 잘 해 주셨습니다! :)

1번 문제에서 패턴1~3과 같은 상수값은 가능하면 최상단에 PATTERN1 등과 같이 대문자로 적어주시면 가시성이 좋아집니다.

수고하셨습니다! :)
