### ISSUE TITLE
박혜준 과제 제출

### ISSUE THREAD

**Issue by margu31** [ai-creatv/algorithm_FDS18#15]
[Homework #1 제출](https://github.com/margu31/JavaScript-Algorithm/tree/main/AlgorithmClass/HW_1)

**Comment by ai-creatv** [comment]
기능 구현을 잘 해 주셨습니다! :)

2번 문제에서 맵1과 맵2를 처리하는 데에 중복코드가 발생하는데, 이것은 함수로 구현해서 사용하시면 가독성이 더 좋아질 것 같습니다 :)

수고하셨습니다!
