### ISSUE TITLE
김효성 과제 제출입니다

### ISSUE THREAD

**Issue by hyorard-b** [ai-creatv/algorithm_FDS18#16]
[과제 1 링크](https://github.com/hyorard-b/TIL/tree/main/algorithm/FDS-HW/HW1)

**Comment by ai-creatv** [comment]
깔끔하고 가독성 좋게 잘 구현해 주셨네요! :)

forEach, reduce 등을 잘 활용해 주셨습니다. 수고하셨습니다 :)
