### ISSUE TITLE
이재훈: 과제 제출입니다

### ISSUE THREAD

**Issue by dannyjaehoon** [ai-creatv/algorithm_FDS18#17]
https://github.com/dannylee9212/data-structure/tree/main/src/list

**Comment by ai-creatv** [comment]
테스트까지 잘 작성하셔서 알고리즘의 동작을 잘 확인할 수 있도록 해 주셨습니다 :)

size 변수를 추가하여 구현을 편하게 하신 부분도 잘 해 주셨습니다.

문자를 넣었을 때 0이 되는 것은, 자료형이 맞지 않는 경우 자료형을 변환하여 입력하기 때문인데요,

실수형은 정수형으로 반올림되어 입력되며, 그 외의 경우 모두 0으로 변환됩니다 :)
