### ISSUE TITLE
서민기: 과제 제출

### ISSUE THREAD

**Issue by minki607** [ai-creatv/algorithm_FDS18#19]
[과제링크](https://github.com/minki607/javascript-exercise/blob/master/data-structure/double-linked-list.js)

**Comment by ai-creatv** [comment]
깔끔하게 잘 작성해 주셨네요!

size변수의 도입과 find 메소드의 도입으로 코드가 많이 간결해 졌습니다. 잘 해주셨습니다 :)

insert에서 index가 마지막 노드 + 1일 때(즉, append와 동일한 동작이어야 할 때)가 구현되지 않은 것으로 보이네요!

prepend를 예외로 처리해주신 것 처럼 append를 해야 하는 상황도 처리해 주시면 좋을 것 같습니다. :)

수고하셨습니다!
