### ISSUE TITLE
박재운 과제 제출합니다

### ISSUE THREAD

**Issue by kmaledev** [ai-creatv/algorithm_FDS18#2]
<img width="1234" alt="Screen Shot 2021-03-06 at 1 01 14 AM" src="https://user-images.githubusercontent.com/72863748/110142092-2847ac00-7e19-11eb-9870-b0899eecc99e.png">

### 코드를 확인하시려면 [💿](https://github.com/wisemett/assignment/blob/master/algorithm/algorithm01/algorithm01.md)를 눌러주세요

**Comment by ai-creatv** [comment]
filter, reduce 등 활용하셔서 깔끔하게 잘 구현하셨네요! :) 가독성도 좋고 깔끔합니다. 수고하셨습니다.
