### ISSUE TITLE
강은진_day02_과제제출

### ISSUE THREAD

**Issue by ejinaaa** [ai-creatv/algorithm_FDS18#21]
미션 완료!!!!!!
근데 array는 아직....
확인 부탁드려용~~~~
https://github.com/ejinaaa/FDS18_algorithm/tree/main/day02

**Comment by ai-creatv** [comment]
기능 구현을 잘 해 주셨습니다! :)

- append는 head부터 찾아갈 필요 없이, tail에서 곧바로 가능한 점 확인해주세요 :)

- insert에서 index가 마지막 노드 + 1일 때(즉, append와 동일한 동작이어야 할 때)가 구현되지 않은 것으로 보이네요!

  prepend를 예외로 처리해주신 것 처럼 append를 해야 하는 상황도 처리해 주시면 좋을 것 같습니다. :)

수고하셨습니다!
