### ISSUE TITLE
김연구 DoublyLinkedList 과제

### ISSUE THREAD

**Issue by yg-0103** [ai-creatv/algorithm_FDS18#22]
https://github.com/yg-0103/TIL/blob/main/algorithm/DoublyLinkedList.js

레포주소입니다 !! ㅎㅎ printInv 는 정확히 무슨뜻인지 몰라서 꼬리부터 접근하는 걸로 했습니다!

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! :)

- 비어있을 때 print()를 동작시킬 경우 오류가 발생하는 문제가 있네요!

- insert에서 index가 마지막 노드 + 1일 때(즉, append와 동일한 동작이어야 할 때)가 구현되지 않은 것으로 보이네요!

  prepend를 예외로 처리해주신 것 처럼 append를 해야 하는 상황도 처리해 주시면 좋을 것 같습니다. :)

수고하셨습니다!
