### ISSUE TITLE
류하준 DoublyLinkedList 과제 제출

### ISSUE THREAD

**Issue by HaJunRyu** [ai-creatv/algorithm_FDS18#23]
죄송합니다 제출이 늦었습니다ㅠㅠ

[과제 링크](https://dev-junn.netlify.app/#/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98&%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0/DoublyLinkedList)입니다!

아마 틀린 부분도 있을것 같은데 혹시 잘못된 부분있으면 피드백 부탁드리겠습니다😂

**Comment by ai-creatv** [comment]
잘 구현해 주셨습니다! :)

setHead에서 prev를 null처리 해주는 부분이 빠져서 print와 printInv의 내용이 달라졌네요!

수고하셨습니다 :)
