### ISSUE TITLE
이재훈 linked queue 과제 제출입니다.

### ISSUE THREAD

**Issue by dannyjaehoon** [ai-creatv/algorithm_FDS18#24]
https://github.com/dannylee9212/data-structure/tree/main/src/queue

**Comment by ai-creatv** [comment]
Linked queue에서 put을 할 때 head의 next에 노드가 연결되지 않는 문제가 있네요! :)

이 문제 때문에 get()을 한번 하면 큐가 무조건 비어버리는 문제가 있습니다.

답안 참고하셔서 문제점 파악해보시기 바랍니다 :) 수고하셨습니다!
