### ISSUE TITLE
과제 제출합니다.

### ISSUE THREAD

**Issue by Wonjuny0804** [ai-creatv/algorithm_FDS18#3]
https://github.com/Wonjuny0804/JavaScript/blob/master/Programmers/allCases.js
https://github.com/Wonjuny0804/JavaScript/blob/master/Programmers/three.js

**Comment by ai-creatv** [comment]
JS 기본 기능들을 이용해서 깔끔하게 잘 구현해 주셨네요 :)

solution 함수의 경우 arrow function으로 구현하시는 것 보다는, 일반적인 함수로 구현해 주시는 것이 컨벤션에 더 맞으니, 참고해주세요!
