### ISSUE TITLE
류하준 과제 제출입니다. (프로그래머스 1단계 스킬체크)

### ISSUE THREAD

**Issue by HaJunRyu** [ai-creatv/algorithm_FDS18#4]
1. [소수찾기](https://github.com/HaJunRyu/Programmers-Algorithm/blob/main/JavaScript/Level_1/%EC%86%8C%EC%88%98%20%EC%B0%BE%EA%B8%B0.js)

소수 찾기는 수업시간때 질문했던 내용이었습니다. 상단에 있는 코드가 제가 처음에  작성한 코드, 결과는 잘 나오지만 효율성 테스트에서 떨어졌고 에라토스테네스의 체 알고리즘을 참조하여 풀었습니다.

2. [완주하지 못한 선수](https://github.com/HaJunRyu/Programmers-Algorithm/blob/main/JavaScript/Level_1/%EC%99%84%EC%A3%BC%ED%95%98%EC%A7%80%20%EB%AA%BB%ED%95%9C%20%EC%84%A0%EC%88%98.js)

완주하지 못한 선수는 저번에 풀었던 문제라 다시 리팩토링 해보려고 했는데 배열 고차함수를 몇개만 사용해도 효율성 테스트에서 떨어졌고 이 문제가 해시 자료구조에 관련된 것 이라는데 사실 제가 지금 해결한것처럼 sort를 해서 비교하는 방식이 해시 자료구조와 관련있는것인지를 잘 모르겠습니다. 각 선수들마다 이름과 상관없이 고유한값들을 부여해서 그것으로 비교해보고싶은데 방법을 잘 모르겠습니다ㅠㅠ

<img width="1688" alt="스크린샷 2021-03-06 오후 5 34 58" src="https://user-images.githubusercontent.com/71176945/110200917-b10b2a00-7ea3-11eb-9f75-b280e771579f.png">

**Comment by ai-creatv** [comment]
가독성 좋게 잘 구현해 주셨습니다 :) 2번 문제에 대한 코멘트 드립니다.

- 우선 sort하여 해결하는 방식은 hash와는 관련이 없습니다. sort한 후에 하나씩 비교하는 방식의 시간복잡도는 O(nlogn)입니다.
  - 정렬: O(nlogn)
  - 비교: O(n)
  - 종합: O(nlogn) + O(nlogn) + O(n) => O(nlogn)
- 선수별로 고유한 id를 부여하는 방식은 특별한 장점이 없습니다.
- hash를 이용한 해결 방식은 map 자료형을 이용하는 것입니다. map 자료형은 Hash table이기 때문에, 자료를 삽입하거나 색인하는 시간 복잡도가 O(1)입니다.
  - map을 이용하여 이름별로 몇명이 있는지 숫자로 기록합니다.
  - 출발에 이름이 있으나, 도착에 이름이 없으면 곧바로 반환합니다.
  - 출발과 도착 모두에 이름이 있으나, 숫자를 비교해 다르면 반환합니다.
