### ISSUE TITLE
김지원_day01_과제제출

### ISSUE THREAD

**Issue by iamkjw77** [ai-creatv/algorithm_FDS18#5]
![image](https://user-images.githubusercontent.com/45993668/110202277-d2bbdf80-7eaa-11eb-848d-5b49d212cf24.png)

[🎁 과제 보기 🎁](https://github.com/iamkjw77/Algorithm_fastcampus/tree/main/homework/day_01)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨네요! 두 문제 모두 가독성 좋게 잘 구현해 주셨습니다 :) 수고하셨습니다!
