### ISSUE TITLE
신봉철_day01_과제제출

### ISSUE THREAD

**Issue by bcround** [ai-creatv/algorithm_FDS18#6]
Day01 [과제레포](https://github.com/bcround/FDS18-Algorithm_Class-HW)입니다!

**Comment by ai-creatv** [comment]
깔끔하게 잘 해주셨습니다 :)

1번의 경우 forEach보다는 for를 쓰셔서 break를 쓰시면 성능이 향상될 것 같네요!

수고하셨습니다 :)
