### ISSUE TITLE
강은진_day01_과제제출

### ISSUE THREAD

**Issue by ejinaaa** [ai-creatv/algorithm_FDS18#7]
https://github.com/ejinaaa/FDS18_algorithm

미션 컴플릿!
확인 부탁드려요오~~

**Comment by ai-creatv** [comment]
기능 구현을 깔끔하게 잘 해주셨습니다 :)

1번 문제에서 상수를 미리 설정해서 해 주신 점도 매우 좋습니다. 수고하셨습니다!
