### ISSUE TITLE
장지혜_1st_Homework_제출

### ISSUE THREAD

**Issue by jjhstoday** [ai-creatv/algorithm_FDS18#8]
[1st_Homework 제출 🙇🏻‍♀️](https://github.com/jjhstoday/Algorithm-Javascript/tree/main/algorithm_FDS18_Homeworks/1)

**Comment by ai-creatv** [comment]
깔끔하게 잘 구현해 주셨습니다! :)

2번 문제에서 몇가지 코멘트 드립니다.
- j를 i부터 n-1까지로 하신 다음 j+1을 사용하셨는데, j를 i+1부터 n까지로 하면 가독성이 더 좋을 것 같습니다 :)
- 삼항연산자를 사용하신 부분이 if문으로 하면 가독성이 더 좋을 것 같습니다 :) 삼항연산자는 좌변이 있어서 무언가 결과를 저장할 때 사용하는 것이 일반적입니다.

수고하셨습니다! :)
