### ISSUE TITLE
한병국 첫번째 과제 제출

### ISSUE THREAD

**Issue by bg-shorthand** [ai-creatv/algorithm_FDS18#9]
https://github.com/bg-shorthand/algorithm_FDS18/blob/master/6_submit_homework/20210306.js

![image](https://user-images.githubusercontent.com/72680186/110209147-2db2fe00-7ece-11eb-850c-2f18c68ad63d.png)

**Comment by ai-creatv** [comment]
기능 구현 깔끔하게 잘 해 주셨습니다. 수고하셨습니다! :)
